services:
  db:
    image: postgres:15-alpine
    container_name: pubquiz-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pubquiz
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pubquiz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pubquiz"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pubquiz-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/pubquiz
      JWT_SECRET: lukamarija
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pubquiz-network


volumes:
  postgres_data:

networks:
  pubquiz-network:
    driver: bridge