import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { AuthProvider } from "../../components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*Neka ovaj element bude visok bar onoliko koliko je visok ekran */}
      <body className="flex flex-col min-h-screen">
        
          

          <main className="flex-grow">  
            <AuthProvider>
              <Navbar />
              {children}
            </AuthProvider>

          </main>
          <Footer />
        
      </body>
    </html>
  );
}
